---
title: "casual_1"
output: html_document
date: "2023-04-06"
---

```{r}
library(car)
library(dplyr)
library(ggplot2)
library(hrbrthemes)
library(GGally)
library(gridExtra)
```

```{r}
daydata <- read.csv("/Users/bach_nguyen/MA 575/Labs/Project/Data/day.csv",header=TRUE)
df = data.frame(daydata)
df = df[-c(22),]
train = df[df$yr == '0',]
validation = df[df$yr == '1',]
attach(train)
```

```{r}
data <- data.frame(casual, temp, atemp, hum, windspeed)
ggpairs(data, upper = list(continuous = wrap("points", alpha = 0.3,    size=0.1)),
lower = list(continuous = wrap('cor', size = 4)))
```

```{r}
par(mfrow=c(2,2))
boxplot(casual~as.factor(season),ylab="casual", xlab="season")
boxplot(casual~as.factor(workingday),ylab="casual", xlab="workingday")
boxplot(casual~as.factor(weathersit),ylab="casual", xlab="weathersit")
boxplot(casual~as.factor(weekday),ylab="casual", xlab="weekday")
```

```{r}
m = lm(log(casual) ~ temp + I(temp^2) + windspeed + as.factor(season)+ as.factor(weathersit)+ as.factor(workingday))
summary(m)
```

```{r}
StanRes <- rstandard(m)
par(mfrow=c(3,3))
plot(temp,StanRes, ylab="Standardized Residuals")
plot(hum,StanRes, ylab="Standardized Residuals")
plot(windspeed,StanRes, ylab="Standardized Residuals")
boxplot(StanRes~as.factor(season),ylab="Standardized Residuals",xlab="season")
boxplot(StanRes~as.factor(workingday),ylab="Standardized Residuals",xlab="workingday")
boxplot(StanRes~as.factor(weathersit),ylab="Standardized Residuals",xlab="weathersit")
```

```{r}
plot(m$fitted.values,log(casual),xlab="Fitted Values")
abline(lsfit(m$fitted.values,log(casual)))
```

```{r}
par(mfrow=c(1,2))
plot(m)
abline(v=2*8/72,lty=2)
```

```{r}
#examine point 18, 27, 239
train[c(18, 27, 239), ] 

```

```{r}
vif(m)
```

```{r}
par(mfrow=c(2,2))
mmp(m,temp)
mmp(m,hum)
mmp(m,windspeed)
mmp(m,m$fitted.values,xlab="Fitted Values")
```

```{r}
library(car)
par(mfrow=c(2,2))
avPlot(m,variable=temp,ask=FALSE, main="")
avPlot(m,variable=windspeed,ask=FALSE, main="")
```

```{r}
ggplot(train[100:200,], aes(x = instant, y = casual)) +
    geom_line(shape=1)
```



```{r}
new_data <- data.frame(instant=validation$instant,temp=validation$temp, windspeed =validation$windspeed,hum=validation$hum, season =validation$season, weathersit=validation$weathersit, workingday=validation$workingday, mnth= validation$mnth, holiday = validation$holiday, weekday=validation$weekday, yr=validation$yr, casual=validation$casual, registered=validation$registered)


output_cnt <- predict(m,se.fit = TRUE, newdata = new_data)

# Create data frame with validation observation and prediction
test = data.frame(validation$cnt,output_cnt$fit*growth, 1:length(output_cnt$fit));
colnames(test)[1] = "Cnt"
colnames(test)[2] = "Prediction"
colnames(test)[3] = "Index"
```

```{r}
ggplot(data = test, aes(x = Index)) +
  geom_line(aes(y = Cnt, color = "Cnt")) + 
  geom_line(aes(y = Prediction, color="Prediction"), linetype="twodash") +  
  scale_color_manual(name = element_blank(), labels = c("Cnt","Prediction"),
                     values = c("coral2", "darkcyan")) + labs(y = "") + 
  ggtitle("Validation")
```

