---
title: "discussion"
output: html_document
date: "2023-04-12"
---

```{r}
library(car)
library(dplyr)
library(ggplot2)
library(hrbrthemes)
library(GGally)
library(gridExtra)
library(nlme)
library(glmnet)
library(RColorBrewer)
```

```{r}
day2010 <- read.csv("/Users/bach_nguyen/Desktop/data/2010-capitalbikeshare-tripdata.csv",header=TRUE)
day2011 <- read.csv("/Users/bach_nguyen/Desktop/data/2011-capitalbikeshare-tripdata.csv",header=TRUE)
day2012_q1 <- read.csv("/Users/bach_nguyen/Desktop/data/2012-capitalbikeshare-tripdata/2012Q1-capitalbikeshare-tripdata.csv", header = TRUE)
day2012_q2 <- read.csv("/Users/bach_nguyen/Desktop/data/2012-capitalbikeshare-tripdata/2012Q2-capitalbikeshare-tripdata.csv", header = TRUE)
day2012_q3 <- read.csv("/Users/bach_nguyen/Desktop/data/2012-capitalbikeshare-tripdata/2012Q3-capitalbikeshare-tripdata.csv", header = TRUE)
day2012_q4 <- read.csv("/Users/bach_nguyen/Desktop/data/2012-capitalbikeshare-tripdata/2012Q4-capitalbikeshare-tripdata.csv", header = TRUE)
day2013_q1 <- read.csv("/Users/bach_nguyen/Desktop/data/2013-capitalbikeshare-tripdata/2013Q1-capitalbikeshare-tripdata.csv", header= TRUE)
day2013_q2 <- read.csv("/Users/bach_nguyen/Desktop/data/2013-capitalbikeshare-tripdata/2013Q2-capitalbikeshare-tripdata.csv", header= TRUE)
day2013_q3 <- read.csv("/Users/bach_nguyen/Desktop/data/2013-capitalbikeshare-tripdata/2013Q3-capitalbikeshare-tripdata.csv", header= TRUE)
day2013_q4 <- read.csv("/Users/bach_nguyen/Desktop/data/2013-capitalbikeshare-tripdata/2013Q4-capitalbikeshare-tripdata.csv", header= TRUE)
day2014_q1 <- read.csv("/Users/bach_nguyen/Desktop/data/2014-capitalbikeshare-tripdata/2014Q1-capitalbikeshare-tripdata.csv", header = TRUE)
day2014_q2 <- read.csv("/Users/bach_nguyen/Desktop/data/2014-capitalbikeshare-tripdata/2014Q2-capitalbikeshare-tripdata.csv", header = TRUE)
day2014_q3 <- read.csv("/Users/bach_nguyen/Desktop/data/2014-capitalbikeshare-tripdata/2014Q3-capitalbikeshare-tripdata.csv", header = TRUE)
day2014_q4 <- read.csv("/Users/bach_nguyen/Desktop/data/2014-capitalbikeshare-tripdata/2014Q4-capitalbikeshare-tripdata.csv", header = TRUE)

```

```{r}
Year <- c("2010", "2011", "2012", "2013", "2014")
Counts <- c(length(day2010$Bike.number), length(day2011$Bike.number), length(day2012_q1$Bike.number) + length(day2012_q2$Bike.number) + length(day2012_q3$Bike.number)+ length(day2012_q4$Bike.number), length(day2013_q1$Bike.number)+length(day2013_q2$Bike.number)+length(day2013_q3$Bike.number)+length(day2013_q4$Bike.number), length(day2014_q1$Bike.number)+length(day2014_q2$Bike.number)+length(day2014_q3$Bike.number)+length(day2014_q4$Bike.number))
df <- data.frame(Year, Counts)
barplot(df$Counts,names.arg=df$Year,xlab="Year",ylab="Rents",col=brewer.pal(5,'PuRd'),
main="Total rents over years",border="black")
#ggplot(df,aes(year,cnt), xlab="Year",ylab="Total Counts")+geom_bar(stat="identity")
```


