---
title: "total_8"
output: html_document
date: "2023-04-10"
---

```{r}
library(car)
library(dplyr)
library(ggplot2)
library(hrbrthemes)
library(GGally)
library(gridExtra)
library(nlme)
```

```{r}
daydata <- read.csv("/Users/bach_nguyen/MA 575/Labs/Project/Data/day.csv",header=TRUE)
df = data.frame(daydata)
set.seed(1)
#sample <- sample(c(TRUE, FALSE), nrow(iris), replace=TRUE, prob=c(0.7,0.3))
#train  <- daydata[sample, ]
#validation   <- daydata[!sample, ]
#df = subset(df, season == 2)
train = df[df$yr == '0',]
validation = df[df$yr == '1',]
train2 <- train[-c(18,27,239,359,328),]
attach(train)
```

```{r}
m= lm(cnt ~ temp+ I(temp^2)+ I(temp^3) + windspeed +as.factor(weathersit))
summary(m)
```

```{r}
StanRes1 <- rstandard(m)
acf(StanRes1,main="Series Standardized Residuals")
```

```{r}
m1 <- gls(cnt ~ temp+ I(temp^3) + windspeed + as.factor(season) +as.factor(weathersit),correlation=corAR1(form=~instant),data=train,method="ML")
summary(m1)
```

```{r}
train$cnt_lag1 <- lag(train$cnt, 1)
train$cnt_lag7 <- lag(train$cnt, 7)
train <- train[complete.cases(train), ]
model <- lm(cnt ~ lag(train$cnt, 7) +temp + I(temp^2) + I(temp^3)+ windspeed+ as.factor(weathersit) + as.factor(season), data = train)
summary(model)
```
