---
title: "total_1"
output: html_document
date: "2023-04-06"
---

```{r}
library(car)
library(dplyr)
library(ggplot2)
library(hrbrthemes)
library(GGally)
library(gridExtra)
```

```{r}
daydata <- read.csv("/Users/bach_nguyen/MA 575/Labs/Project/Data/day.csv",header=TRUE)
df = data.frame(daydata)
train = df[df$yr == '0',]
validation = df[df$yr == '1',]
attach(train)
```

```{r}
data <- data.frame(cnt, temp, atemp, hum, windspeed)
ggpairs(data, upper = list(continuous = wrap("points", alpha = 0.3,    size=0.1)),
lower = list(continuous = wrap('cor', size = 4)))
```

```{r}
par(mfrow=c(2,2))
boxplot(cnt~as.factor(season),ylab="total", xlab="season")
boxplot(cnt~as.factor(workingday),ylab="total", xlab="workingday")
boxplot(cnt~as.factor(weathersit),ylab="total", xlab="weathersit")
boxplot(cnt~as.factor(weekday),ylab="total", xlab="weekday")
```

```{r}
#drop these rows from train
m= lm(cnt ~ temp+ I(temp^2)  + as.factor(holiday) + windspeed + as.factor(season)+ as.factor(weathersit) + as.factor(mnth))
summary(m)
```

```{r}
StanRes <- rstandard(m)
par(mfrow=c(3,3))
plot(temp,StanRes, ylab="Standardized Residuals")
plot(hum,StanRes, ylab="Standardized Residuals")
plot(windspeed,StanRes, ylab="Standardized Residuals")
boxplot(StanRes~as.factor(season),ylab="Standardized Residuals",xlab="season")
boxplot(StanRes~as.factor(workingday),ylab="Standardized Residuals",xlab="workingday")
boxplot(StanRes~as.factor(weathersit),ylab="Standardized Residuals",xlab="weathersit")
```

```{r}
plot(m$fitted.values,cnt,xlab="Fitted Values")
abline(lsfit(m$fitted.values,cnt))
```

```{r}
par(mfrow=c(2,2))
plot(m)
abline(v=2*8/72,lty=2)
```

```{r}
#Threshold
largeleverage=10/count(train)
print(largeleverage)

train$hatvalues <- hatvalues(m)
leverage<-train[order(-train$hatvalue), ]
```

Need to examine row 27, 239, 341 (dropped)

```{r}
vif(m)
```

```{r}
par(mfrow=c(2,2))
mmp(m,temp)
mmp(m,hum)
mmp(m,windspeed)
mmp(m,m$fitted.values,xlab="Fitted Values")
```

```{r}
library(car)
par(mfrow=c(2,2))
avPlot(m,variable=temp,ask=FALSE, main="")
avPlot(m,variable=windspeed,ask=FALSE, main="")
```
