---
title: "total_7"
output: html_document
date: "2023-04-10"
---

```{r}
library(car)
library(dplyr)
library(ggplot2)
library(hrbrthemes)
library(GGally)
library(gridExtra)
library(nlme)
library(glmnet)
```

```{r}
daydata <- read.csv("/Users/bach_nguyen/MA 575/Labs/Project/Data/day.csv",header=TRUE)
df = data.frame(daydata)
set.seed(1)
#sample <- sample(c(TRUE, FALSE), nrow(iris), replace=TRUE, prob=c(0.7,0.3))
#train  <- daydata[sample, ]
#validation   <- daydata[!sample, ]
#df = subset(df, season == 2)
train = df[df$yr == '0',]
validation = df[df$yr == '1',]
#train2 <- train[-c(18,27,239,359,328),]
attach(train)
```

```{r}

y <- train$cnt
train$temp_square <- train$temp^2
train$temp_cube <- train$temp^3
x_train <- data.matrix(train[, c('temp','temp_square','temp_cube', 'hum', 'windspeed')])

validation$temp_square <- validation$temp^2
validation$temp_cube <- validation$temp^3
x_test <- data.matrix(validation[, c('temp','temp_square','temp_cube', 'hum', 'windspeed')])
#fit lasso regression model using k-fold cross-validation
cv_model <- cv.glmnet(x_train, y, alpha = 1)
best_lambda <- cv_model$lambda.min

#display optimal lambda value
best_lambda



```

```{r}
#view plot of test MSE's vs. lambda values
plot(cv_model)

#view coefficients of best model
best_model <- glmnet(x_train, y, alpha = 1, lambda = best_lambda)
coef(best_model)

#make a prediction for the response value of a new observation


output_t <- predict(best_model, s = best_lambda, newx = x_train)
output_v <- predict(best_model, s = best_lambda, newx = x_test)
#find R-squared of model on training data
y_predicted <- predict(best_model, s = best_lambda, newx = x_train)

sst <- sum((y - mean(y))^2)
sse <- sum((y_predicted - y)^2)

rsq <- 1 - sse/sst
rsq
```

```{r}
ResMLS <- train$cnt - output_t

# Mean Square Error for training data
cat("MSE for training:", mean((ResMLS)^2))
cat("\n")
cat("RMSE for training:", sqrt(mean((ResMLS)^2)))

cat("\n")
cat("\n")

#Mean Square Error for validation (year: 2012)
ResMLSValidation <- validation$cnt - output_v
cat("MSE for validation:", mean((ResMLSValidation)^2))
cat("\n")
cat("RMSE for validation:", sqrt(mean((ResMLSValidation)^2)))
cat("\n")
```

```{r}
mod <- glmnet(x = x_train, y = y, alpha = 1)
plot(mod, xvar = "lambda", label = TRUE)
```
