---
title: "total_9"
output: html_document
date: "2023-04-11"
---

```{r}
library(car)
library(dplyr)
library(ggplot2)
library(hrbrthemes)
library(GGally)
library(gridExtra)
library(nlme)
library(glmnet)
```

```{r}
daydata <- read.csv("/Users/bach_nguyen/MA 575/Labs/Project/Data/day.csv",header=TRUE)
df = data.frame(daydata)
df[df==-200]<-NA
df <- na.omit(df)
#df = df[-c(239,266, 328,22),] #there are high leverage, will need reasons to justify removing
df = df[-c(22),]
train = df[df$yr == '0',]
validation = df[df$yr == '1',]
attach(train)
```

```{r}
#str(train)
#colSums(is.na(train))
```

```{r}
data <- data.frame(cnt, temp, temp^2, temp^3)
ggpairs(data, upper = list(continuous = wrap("points", alpha = 0.3,    size=0.1)),
lower = list(continuous = wrap('cor', size = 4)))
```


```{r}
par(mfrow=c(2,2))
boxplot(casual~as.factor(weekday),ylab="casual", xlab="weekday for casual", names = c('mon', 'tue','wed','thr','fri','sat','sun') )
boxplot(registered~as.factor(weekday),ylab="registered", xlab="weekday for registered", names = c('mon', 'tue','wed','thr','fri','sat','sun'))
```


```{r}
m <-  lm(cnt~temp + I(temp^2)+ I(temp^3) + windspeed + as.factor(weathersit) + as.factor(season))
summary(m)
```

```{r}
var_pool <- data.frame(cnt, temp, atemp, hum, windspeed, I(temp^2), I(temp^3), I(windspeed^2))
```


```{r}
#BIC backward
n <- length(var_pool[,1])
backBIC <- step(m,direction="backward", data=var_pool, k=log(n))
```

```{r}
#AIC backward
backAIC <- step(m,direction="backward", data=var_pool)
```







```{r}
# forward AIC
m2 <- lm(cnt~1,data=var_pool)
forwardAIC <- step(m2,scope=list(lower=~1, 
upper=~temp + I(temp^2)+ I(temp^3) + windspeed+ as.factor(season) + as.factor(weathersit)),direction="forward", data=var_pool)
```


```{r}
# forward BIC
forwardBIC <- step(m2,scope=list(lower=~1, 
upper=~temp + I(temp^2)+ I(temp^3) + windspeed+ as.factor(season) + as.factor(weathersit)),
direction="forward", data=var_pool,k=log(n))
```

```{r}
var_pool <- data.frame(cnt, temp, atemp, hum, windspeed, I(temp^2), I(temp^3), I(windspeed^2))

#AIC backward
backAIC <- step(m,direction="backward", data=var_pool)

#BIC backward
n <- length(var_pool[,1])
backBIC <- step(m,direction="backward", data=var_pool, k=log(n))

# forward AIC
m2 <- lm(cnt~1,data=var_pool)
forwardAIC <- step(m2,scope=list(lower=~1, 
upper=~temp + I(temp^2)+ I(temp^3) + windspeed+ as.factor(season) + as.factor(weathersit)),direction="forward", data=var_pool)

# forward BIC
forwardBIC <- step(m2,scope=list(lower=~1, 
upper=~temp + I(temp^2)+ I(temp^3) + windspeed+ as.factor(season) + as.factor(weathersit)),
direction="forward", data=var_pool,k=log(n))
```


```{r}
start <- mean(cnt[mnth == seq(from = 1, to = 5, by =1)])
#start <- mean(cnt[mnth == c(1,2,3,4,5)])
end <- mean(cnt[mnth == seq(from=6, to =12, by = 1)])
#end <- mean(cnt[mnth == c(6,7,8,9,10,11,12)])
growth<-end/start
cat("annual rate is: ", growth)
```


--------------------------
Validation:

```{r}
new_data <- data.frame(instant=validation$instant,temp=validation$temp, windspeed =validation$windspeed,hum=validation$hum, season =validation$season, weathersit=validation$weathersit, workingday=validation$workingday, mnth= validation$mnth, holiday = validation$holiday, weekday=validation$weekday, yr=validation$yr)


output_cnt <- predict(m,se.fit = TRUE, newdata = new_data)

# Create data frame with validation observation and prediction
test = data.frame(validation$cnt,output_cnt$fit, 1:length(output_cnt$fit));
colnames(test)[1] = "Cnt"
colnames(test)[2] = "Prediction"
colnames(test)[3] = "Index"

```

```{r}
#Calculate MSE
# Residuals for training data
ResMLS <- resid(m)

# Mean Square Error for training data
cat("MSE for training:", mean((ResMLS)^2))
cat("\n")
cat("RMSE for training:", sqrt(mean((ResMLS)^2)))

cat("\n")
cat("\n")

#Mean Square Error for validation (year: 2012)
ResMLSValidation <- validation$cnt - output_cnt$fit
cat("MSE for validation:", mean((ResMLSValidation)^2))
cat("\n")
cat("RMSE for validation:", sqrt(mean((ResMLSValidation)^2)))
cat("\n")
#cat("mean diff between validation$cnt and training$cnt", mean(validation$cnt - train$cnt))
```
```{r}
cat("Relative MSE of training: ",mean((ResMLS)^2) / mean((m$fitted.values)^2),"\n" )
cat("Relative MSE of validation: ",mean((ResMLSValidation)^2) / mean((validation$cnt)^2),"\n") 
```



```{r}
ggplot(data = test, aes(x = Index)) +
  geom_line(aes(y = Cnt, color = "Cnt")) + 
  geom_line(aes(y = Prediction, color="Prediction"), linetype="twodash") +  
  scale_color_manual(name = element_blank(), labels = c("Cnt","Prediction"),
```


```{r}
values = c("orchid", "royalblue3")) + labs(y = "") + 
  ggtitle("Validation")
```

```{r}
test2 = test[100:200,]

# Plot GroundCO vs Prediction for Validation Data Set 
ggplot(data = test2, aes(x = Index)) +
  geom_line(aes(y = Cnt, color = "Cnt")) + 
  geom_line(aes(y = Prediction, color="Prediction"), linetype="twodash") +  
  scale_color_manual(name = element_blank(), labels = c("Cnt","Prediction"),
                     values = c("coral2", "darkcyan")) + labs(y = "") +
  ggtitle("Validation")
```


